### ISSUE TITLE
이클립스에서 한글이 깨져요!

### ISSUE THREAD

**Issue by MinSeongKyeong** [MinSeongKyeong/sw#1]
저희 이거 해결해야 할것같아요. 이클립스에서 한글이 깨져서 나와요.
아마 인코딩?문제겠죠??

**Comment by jiyoung464** [comment]
Window -> preferences -> General -> workspace -> 하단에 text file encoding 부분을 default 에서 other에 있는 UTF-8로 바꿔서 해야하나봐요.

이미 올려진 파일은 preferences-> General -> content Types -> text -> java source file 선택해서 default encoding 부분을 UTF-8이나 EUC-KR로 update 하면 바로 보여요!

**Comment by hj-dev-log** [comment]
오 완전 해결 됐습니다. 고맙습니다!
