### ISSUE TITLE
studentlist를 찾을 수 없다고 떠요! 

### ISSUE THREAD

**Issue by jiyoung464** [MinSeongKyeong/sw#5]
studentlist.txt 라고 확장자명을 붙여줘야 할까요?

**Comment by sophia1023** [comment]
어디에 확장자명 말하는건가요? update 코드에서??

**Comment by hj-dev-log** [comment]
임시 파일이니 다시 만들고 push 하셔도 될거 같아요.

**Comment by jiyoung464** [comment]
확장자명은 코드안에서 "studentlist.txt"라고 되어 있고,
제가 확장자명을 붙여준 거는 파일 자체를 refactor에서 이름바꾸기 한거에요
지금 refactor로 파일명 자체를 "studentlist.txt"라고 바꿨는데도 오류가 나네요...

**Comment by jiyoung464** [comment]
내용을 적지 않고 close 해버려서 다시 reopen 했습니다!

src폴더를 root폴더로 인식하고 src 안에 "studentlist.txt" 파일을 넣어놨었는데
root 폴더가 프로젝트 폴더라고 해요..
그래서 SoGong 프로젝트 폴더로 move 시켜서 더이상 FileNotFoundException이 뜨지 않습니다!
