### ISSUE TITLE
update 모듈 질문 있습니다.

### ISSUE THREAD

**Issue by hj-dev-log** [MinSeongKyeong/sw#7]
없는 학번을 업데이트 하려 할때 어떻게 처리할 계획이신가요?

**Comment by jiyoung464** [comment]
아직 없는 학번 업데이트하는건 구현하지 않았어요!!
없는 학번을 치면 해당 학번이 없다고 프린트 해준 다음, 다시 학번을 고르라고 만들어 볼게요!!
